### ISSUE TITLE
i not gonna sell it

### ISSUE THREAD

**Issue by alonalibarmn** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#10]
why when i try to injact it it say THIS IS PASTED LMAFO FIX UR SELF i dont try to sell it i just want to use it

**Comment by Visual9999** [comment]
not in my src wtf

**Comment by Piehthyte** [comment]
menu.cpp, line 434 quite clearly says AddMarker(window, width, height, localPlayerLocation, pawn, "THIS IS PASTED LMFAO FIX UR SELF", ({ 1.0f, 0.0f, 0.0f, 1.0f }));

**Comment by Piehthyte** [comment]
https://github.com/Visual9999/FortniteCheatSRCUpdateEveryUpdate/blob/1c0aee759faacea1ac3a5fa0b25ec21d555e4684/FortniteCheatSRCUpdateEveryUpdate/Source%20Files/menu/menu.cpp#L434

**Comment by Piehthyte** [comment]
Did you dev this or paste this?

**Comment by alonalibarmn** [comment]
so what i gonna do someone can give me fix one?

**Comment by Piehthyte** [comment]
I would try to help you out but I am still learning what the script does. If no one can help you by the time I figure it all out then I will try my best.

**Comment by Visual9999** [comment]
hahh you mean this yes i can fix it if you want

**Comment by alonalibarmn** [comment]
yes plz fix it and update it ty 👍

**Comment by dschaf** [comment]
@alonalibarmn skid hey visual u might not remember me its hippie gamer inverses friend could u post how to update source /get cigs and patterns?

**Comment by Nom-Youtube** [comment]
its just a simple function drawing text on the canvas lol its an easy fix

**Comment by Nom-Youtube** [comment]
> @alonalibarmn skid hey visual u might not remember me its hippie gamer inverses friend could u post how to update source /get cigs and patterns?

so um usually people dump them or find them on UC but the fortnite UC forum is only open to users with 5 posts or more so yeah same with sigs

**Comment by Visual9999** [comment]
i already updated sigs.
