### ISSUE TITLE
Silent Aim i fixing 

### ISSUE THREAD

**Issue by dschaf** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#13]
hey mate imma fix silent aim today would u like the updated source when done?

**Comment by SammySiS** [comment]
why not lol

**Comment by Visual9999** [comment]
you mean you know fix or what?

**Comment by dschaf** [comment]
![image](https://user-images.githubusercontent.com/46796744/94205070-fcabb780-feb1-11ea-891a-1f37f78d0941.png)
if u have this source im not suggest pasting i fucked it up and cant find it but it has a working silent aimbot if u can find it u can fix the silent aimbot with ease

**Comment by dschaf** [comment]
@Visual9999 maybe we can fix it together on discord 
or come up with a publicly good paste to knock out all these scammers /skids]
i got a question also do u think u  could teach me how to pattern scan and how to get cigs? if u do ill add commits/updated offsets /pattern/cigs when u dont have a chance too 
Contact Information
Youtube : ClanBlackscop
Discord : 𝐻𝓲P҉P҉i̸E̥ͦG͜͡a̸m̥ͦ𝙚𝑟✞✔#1564

**Comment by Visual9999** [comment]
i dont use covid src and in covid is silent not fixed.
in my src patterns and sigs are the updated. (newest patch : ))
silent is an other fix

**Comment by Visual9999** [comment]
in the src is silent not working
