### ISSUE TITLE
.sln crash for on 

### ISSUE THREAD

**Issue by Izox1230** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#14]
when I open the .sln file and start it up I have some error here is a different picture of the error I can have

![image](https://user-images.githubusercontent.com/71902565/94309326-6afe8180-ff67-11ea-9097-e5ba9faed40d.png)

![image](https://user-images.githubusercontent.com/71902565/94309337-705bcc00-ff67-11ea-8645-e5dc1e945a2e.png)

![image](https://user-images.githubusercontent.com/71902565/94309347-75208000-ff67-11ea-9799-af9b2c253e8a.png)

**Comment by ytmcgamer** [comment]
because source pasted from me and he is shit
