### ISSUE TITLE
Im having an error. Can anyone help?

### ISSUE THREAD

**Issue by GrenadeVisuals** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#19]
Everyime i try to do this is pops up "Failed To Find Calculateshot" then a few seconds later it pops up with "the application has hung and will now close" Any reason why (yes im on 1909)

**Comment by Visual9999** [comment]
redownload src no error for me. (download not the relaese its outdated)

**Comment by Visual9999** [comment]
i published new release just download

**Comment by GrenadeVisuals** [comment]
Hey thanks. i semi got it working. its working but when i inject the cheat like my mouse becomes inactive...
