### ISSUE TITLE
offsets now nigger

### ISSUE THREAD

**Issue by Tescoo** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#22]
give offsets monkey

**Comment by SENSE66667** [comment]
Engine::World::Levels = 0x138
Engine::World::PersistentLevel = 0x30
Engine::GameInstance::LocalPlayers = 0x38
Engine::World::OwningGameInstance = 0x180
Engine::Controller::ControlRotation = 0x288
Engine::PlayerController::PlayerCameraManager = 0x2B8
Engine::PlayerController::AcknowledgedPawn = 0x2A0
Engine::Pawn::PlayerState = 0x240
Engine::Actor::RootComponent = 0x130
Engine::Character::Mesh = 0x280
Engine::SceneComponent::RelativeLocation = 0x11C
Engine::SceneComponent::ComponentVelocity = 0x140
Engine::StaticMeshComponent::StaticMesh = 0x478
Engine::SkinnedMeshComponent::CachedWorldSpaceBounds = 0x5F8
Engine::Actor::CustomTimeDilation = 0x98
PlayerController = 0x30
FortniteGame::Offsets::FortniteGame::FortWeapon::LastFireTimeVerified = 0x8D8
FortniteGame::Offsets::FortniteGame::FortWeapon::LastFireTime = 0x8D4
FortniteGame::FortPawn::bIsDBNO = 0x552
FortniteGame::FortPawn::bIsDying = 0x538
FortniteGame::FortPlayerStateAthena::TeamIndex = 0xE88
FortniteGame::FortPickup::PrimaryPickupItemEntry = 0x298
FortniteGame::FortItemDefinition::DisplayName = 0x70
FortniteGame::FortItemDefinition::Tier = 0x54
FortniteGame::FortItemEntry::ItemDefinition = 0x18
FortniteGame::FortPawn::CurrentWeapon = 0x5C0
FortniteGame::FortWeapon::WeaponData = 0x378
FortniteGame::FortWeapon::LastFireAbilityTime = 0xAD0
FortniteGame::FortWeaponItemDefinition::WeaponStatHandle = 0x7D8
FortniteGame::FortProjectileAthena::FireStartLoc = 0x868
FortniteGame::FortBaseWeaponStats::ReloadTime = 0xFC
FortniteGame::FortBaseWeaponStats::ReloadScale = 0x100
FortniteGame::FortBaseWeaponStats::ChargeDownTime = 0x12C
FortniteGame::FortRangedWeaponStats::RecoilHoriz = 0x200
FortniteGame::FortRangedWeaponStats::RecoilVert = 0x1F0
FortniteGame::FortRangedWeaponStats::RecoilDownsightsMultiplier = 0x21C
FortniteGame::FortRangedWeaponStats::Spread = 0x15C
FortniteGame::FortRangedWeaponStats::SpreadDownsights = 0x160
FortniteGame::FortRangedWeaponStats::StandingStillSpreadMultiplier = 0x164
FortniteGame::FortRangedWeaponStats::AthenaJumpingFallingSpreadMultiplier = 0x16C
FortniteGame::FortRangedWeaponStats::AthenaCrouchingSpreadMultiplier = 0x168
FortniteGame::FortRangedWeaponStats::AthenaSprintingSpreadMultiplier = 0x21C
FortniteGame::FortRangedWeaponStats::MinSpeedForSpreadMultiplier = 0x174
FortniteGame::FortRangedWeaponStats::MaxSpeedForSpreadMultiplier = 0x178
FortniteGame::BuildingContainer::bAlreadySearched = 0xC91
Offsets::Engine::Controller::RemoteViewPitch = 0x232
PlayerController = 0x30
RelativeRotation = 0x128
BoostCoolDown = 0x50C
BoostDuration = 0x508
BoostForce = 0x500
BoostMaxSpeedKmh = 0x504
LiftForce = 0x4A4
MaxLiftSpeedKmh = 0x4A8
MaxStrafeSpeedKmh = 0x498
StrafeForce = 0x490
BoostMinPushForce = 0x4A0
BoostSteeringMultiplier = 0x4F4
BoostTopSpeedForceMultiplier = 0x4A4
BoostTopSpeedMultiplier = 0x4A8
LandMaxSpeedSteeringAngle = 0x504
LandMinSpeedSteeringAngle = 0x500
LandPushForceMultiplier = 0x4B4
LandSteeringMultiplier = 0x4FC
LandTopSpeedMultiplier = 0x4B0
SpectatorPawn = 0x548
bIsReloadingWeapon = 0x2B1
PlayerState = 0x22A
AmmoCount = 0x94C

**Comment by Generaltruthan** [comment]
how do u get the offsets?

**Comment by Visual9999** [comment]
its easy
