### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by H1PPIEGAMER** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#28]
its dschaf could u add me on discord ? 𝐻𝓲P҉P҉i̸E̥ͦG͜͡a̸m̥ͦ𝙚𝑟✞✔#2307
i have a few questions
i have the fix for silent aim too and i dont want to say that your source doesnt work without testing a proper driver and i was wondering if u could send me a newer driver its a pain to make them but if its not the driver then the crashing has not been fixed hope u see this

**Comment by ReflexReborn** [comment]
The guy is crazy the crashing isn’t fixed and also Hippie gamer thank u for your free contributions to the community <3

**Comment by H1PPIEGAMER** [comment]
dont be gay my guy i dont even know who u are tbh but np i enjoy what i do

**Comment by H1PPIEGAMER** [comment]
how did u even find my comment

**Comment by Visual9999** [comment]
reflex reborn stupid bitch IT DOSENT CRASH IT ONLY GIVES YOU A FUCKING ERROR RELFEX LOVEFN PASTER NIGGA

**Comment by Visual9999** [comment]
silent works do memory and silent on and it works kekw IT HAS WORKED

**Comment by H1PPIEGAMER** [comment]
how do i pattern scan ? what is the latest method
