### ISSUE TITLE
nigger

### ISSUE THREAD

**Issue by Tescoo** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#29]
give me new bullettp update smelly nigger

**Comment by J3X2BZ** [comment]
tesco do you have fix to aimbot and esp not working aka the CalculateProjectionMatrixGivenView i think thats the sig i need to fix idk dm me: Nocturn#1337

**Comment by Tescoo** [comment]
> tesco do you have fix to aimbot and esp not working aka the CalculateProjectionMatrixGivenView i think thats the sig i need to fix idk dm me: Nocturn#1337

yes i do just not giving it to anyone

**Comment by Visual9999** [comment]
i have it tooooo but why should i release it?
