### ISSUE TITLE
update

### ISSUE THREAD

**Issue by 3481282596** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#3]
My good brother, you just changed the menu, but you didn't update the offset

**Comment by Visual9999** [comment]
BRO OFFSETS UPDATED.

**Comment by Visual9999** [comment]
its already updated like 3days ago.
you can try to inject it works.

**Comment by 3481282596** [comment]
The injection just crashed bro

**Comment by Visual9999** [comment]
you first need to use a mapper like kdmapper or idk.

**Comment by Visual9999** [comment]
and before you say i have to do something i am not dumb and i already have updated offsets etc.
; )

**Comment by 3481282596** [comment]
OK Thanks bro.
