### ISSUE TITLE
HOW TO FIX  SOURCE

### ISSUE THREAD

**Issue by Avapt** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#30]
Go to util.cpp find "Failed to find CalculateProjectionMatrixGivenView" (that error is shown and this is what needs to be fixed)
you see where the x##\ etc is, replace it with 

\xE8\x00\x00\x00\x00\x48\x8B\x47\x30\xF3\x0F\x10\x45 

after that, a little more to right you'll see "xx??" something like that, replace it with 

x????xxxxxx

after that, build the project, grab the dll, inject into fortnite.

have fun skids 👍

**Comment by Avapt** [comment]
btw esp, and aimbot dont work, go to core.cpp and fix urself lol, if i feel nice i will let u know

**Comment by Tescoo** [comment]
hmm, so you are stupid...... thats not the sig and aimbot and esp isnt broken, i have the correct sig, all i had to update was like 5 offsets and the sig. thats not the correct sig so dont waste your time!

**Comment by Avapt** [comment]
whats the correct sig then? 

Asked a friend that also has everything working, exact same sig, whats your sig then.
Broken also means not working, if something is not working, its broken, so fix it yourself. exaclty what i said in the comments

**Comment by Visual9999** [comment]
its false pattern retard
