### ISSUE TITLE
update CalculateProjectionMatrixGivenView

### ISSUE THREAD

**Issue by FannieMC** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#32]
Failed to find CalculateProjectionMatrixGivenView

**Comment by Avapt** [comment]
Go to util.cpp find "Failed to find CalculateProjectionMatrixGivenView" (that error is shown and this is what needs to be fixed)
you see where the x##\ etc is, replace it with

\xE8\x00\x00\x00\x00\x48\x8B\x47\x30\xF3\x0F\x10\x45

after that, a little more to right you'll see "xx??" something like that, replace it with

x????xxxxxx

after that, build the project, grab the dll, inject into fortnite.

(aimbot and esp doesnt work so fix that yourself)
