### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by KalterHauch** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#33]
Hey,
I need help with updating your source, idk what i need to do :/
Can you add me on Discord: UnkownUser#1047

**Comment by Visual9999** [comment]
you only need to update the ons sig but i dont want the make it public because yes.

**Comment by dschaf** [comment]
damn he gave up on us

**Comment by dschaf** [comment]
yo visuals just fixed projectilematrixview myself XD

**Comment by dschaf** [comment]
thanks my friend for the hint
