### ISSUE TITLE
FULL errors ( without modification )

### ISSUE THREAD

**Issue by sysysysy242** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#34]
I get that :  Unexpected end of file when searching for a precompiled header. Did you forget to add '#include "pch.h"' to your source?	D:\Bureau\FortniteCheatSRCUpdateEveryUpdate-master\FortniteCheatSRCUpdateEveryUpdate\Source Files\core\core.cpp

with 14 other files ....

**Comment by Zetolac** [comment]
😂 Mdr t'es là 
Ajoute moi Discord je t'aide : Zetolac#0001

**Comment by sysysysy242** [comment]
C bn
