### ISSUE TITLE
Doesnt work anymore 

### ISSUE THREAD

**Issue by Swifty1337** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#38]
discord overlay hook is patched and the cheat doesnt work anymore can u pls fix

**Comment by ytmcgamer** [comment]
discord overlay hook isn't fucking patched retard visual the retarded skid in Fortnite scene is just too retarded to update 5 sigs lmao

**Comment by VelocityX** [comment]
its not patched... the sig was changed, learn some c++ first :)
