### ISSUE TITLE
Damn i Cant ....

### ISSUE THREAD

**Issue by dschaf** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#39]
Damn i cant believe they finally patched the discord hook what happens if we make a bypass element to run discord on down graded services/servers/currentpoin ? would it make it work again

**Comment by 700montes** [comment]
They didn't patched Discord Hook you ape, they only changed the hk_present signature to hook present.

**Comment by dschaf** [comment]
> They didn't patched Discord Hook you ape, they only changed the hk_present signature to hook present.

last time i checked apes lives in jungle i dont know who u think u are ive been around for a long time in the fortnite community

**Comment by sysysysy242** [comment]
How to ge hk_present signature

**Comment by 700montes** [comment]
> > They didn't patched Discord Hook you ape, they only changed the hk_present signature to hook present.
> 
> last time i checked apes lives in jungle i dont know who u think u are ive been around for a long time in the fortnite community

apes live in jungle DUDE OMG
