### ISSUE TITLE
imagine cant updating discordhook 🤡

### ISSUE THREAD

**Issue by ytmcgamer** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#43]
like it's sad that you cant fucking update 5 sigs from DiscordHook, and then you're saying it "unsupported" 🤡😂 better goto UC and find them 🤡

**Comment by dschaf** [comment]
> like it's sad that you cant fucking update 5 sigs from DiscordHook, and then you're saying it "unsupported" 🤡😂 better goto UC and find them 🤡

or he could use ida and the ref to find them easily anyways how did u get around dxgi not working is there a new module

**Comment by dschaf** [comment]
i can add the minhook if @Visual9999 if u can fix the injection part

**Comment by 700montes** [comment]
> > like it's sad that you cant fucking update 5 sigs from DiscordHook, and then you're saying it "unsupported" 🤡😂 better goto UC and find them 🤡
> 
> or he could use ida and the ref to find them easily anyways how did u get around dxgi not working is there a new module?
why you talk when you don't even know what you're saying?
do you even know what's a xref? and what do you mean dxgi not working???
