### ISSUE TITLE
dude u can still use discord overlay

### ISSUE THREAD

**Issue by DATA6666** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#44]
here are the new sigs that u need to update:
56 57 53 48 83 EC 30 44 89 C6

now update it bc im a lazy nig <3

+rep anyone? XD

**Comment by 700montes** [comment]
there was totally 0 issues about that and ofcourse 0 people have this signature op release thx +rep ah no fuck no +rep on githuub

**Comment by dschaf** [comment]
> here are the new sigs that u need to update:
> 56 57 53 48 83 EC 30 44 89 C6
> 
> now update it bc im a lazy nig <3
> 
> +rep anyone? XD

which one is it theres 5

**Comment by dschaf** [comment]
im using minhook on mine lol i coverted discord to min

**Comment by ytmcgamer** [comment]
yes ik this retard called visual copying my idea and cant even paste discord hook
