### ISSUE TITLE
PLEASE UPDATE

### ISSUE THREAD

**Issue by dschaf** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#45]
my guy all u have to do is download minhook.h and minhook.lib and the delete the discord hooks and setup minhook

**Comment by VelocityX** [comment]
it takes 5 minutes to do lmfao, why dont you do it? or just update the new discord hook which is even easier.

**Comment by dschaf** [comment]
> it takes 5 minutes to do lmfao, why dont you do it? or just update the new discord hook which is even easier.

i did along with multiple other sources like neutron and other source like true aim and hyper
