### ISSUE TITLE
Pull request for a full update 

### ISSUE THREAD

**Issue by paster44** [Visual9999/FortniteCheatSRCUpdateEveryUpdate#46]
I could just do a pull request updating the whole source if you are willing to do that?

**Comment by Visual9999** [comment]
do if you want i just have no time in my fucking live

**Comment by paster44** [comment]
> do if you want i just have no time in my fucking live

Updated everything aimbot, esp, discord hook all working ill make a pull request now all you have to do is rewrite the readme

**Comment by paster44** [comment]
I will make the pull request now
